create table "public"."Destinations" (
    "Destination" text,
    "Region" text,
    "Country" text,
    "Category" text,
    "Latitude" double precision,
    "Longitude" double precision,
    "Approximate Annual Tourists" text,
    "Currency" text,
    "Majority Religion" text,
    "Famous Foods" text,
    "Language" text,
    "Best Time to Visit" text,
    "Cost of Living" text,
    "Safety" text,
    "Cultural Significance" text,
    "Description" text,
    "id" bigint generated by default as identity not null
);


alter table "public"."Destinations" enable row level security;

CREATE UNIQUE INDEX "Destinations_id_key" ON public."Destinations" USING btree (id);

CREATE UNIQUE INDEX "Destinations_pkey" ON public."Destinations" USING btree (id);

alter table "public"."Destinations" add constraint "Destinations_pkey" PRIMARY KEY using index "Destinations_pkey";

alter table "public"."Destinations" add constraint "Destinations_id_key" UNIQUE using index "Destinations_id_key";

grant delete on table "public"."Destinations" to "anon";

grant insert on table "public"."Destinations" to "anon";

grant references on table "public"."Destinations" to "anon";

grant select on table "public"."Destinations" to "anon";

grant trigger on table "public"."Destinations" to "anon";

grant truncate on table "public"."Destinations" to "anon";

grant update on table "public"."Destinations" to "anon";

grant delete on table "public"."Destinations" to "authenticated";

grant insert on table "public"."Destinations" to "authenticated";

grant references on table "public"."Destinations" to "authenticated";

grant select on table "public"."Destinations" to "authenticated";

grant trigger on table "public"."Destinations" to "authenticated";

grant truncate on table "public"."Destinations" to "authenticated";

grant update on table "public"."Destinations" to "authenticated";

grant delete on table "public"."Destinations" to "service_role";

grant insert on table "public"."Destinations" to "service_role";

grant references on table "public"."Destinations" to "service_role";

grant select on table "public"."Destinations" to "service_role";

grant trigger on table "public"."Destinations" to "service_role";

grant truncate on table "public"."Destinations" to "service_role";

grant update on table "public"."Destinations" to "service_role";


